name: Hello

on:
  workflow_dispatch:
    inputs:
      token:
        description: Visible
        required: true
        default: '1'
      set_rft:
        description: Set rft?
        required: true
        default: '1'
      name:
        description: version name
        default: ''
      release_notes:
        description: Release notes
        default: ''

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello
        uses: iliakologrivov/vkt_new_product_version@master
        with:
          token: '123123'
          product_id: 9999
          visible: 1
          set_rft: 1