name: on create tag

on:
  push:
    tags:
      - '*'

jobs:
  createVersionOnPush:
    runs-on: ubuntu-latest
    name: Create new product version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create new product version
        uses: iliakologrivov/vkt_new_product_version@master
        with:
          token: '123123'
          product_id: 9999
          visible: 1
          set_rft: 1
