name: After Release

on:
  release:
    types: [published]

jobs:
  createVersionOnRelease:
    runs-on: ubuntu-latest
    name: Create new product version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create new product version
        uses: iliakologrivov/vkt_new_product_version@master
        env:
          API_TOKEN: ${{ secrets.PRODUCT_API_TOKEN }}
        with:
          product_id: 2478
          title: "${{ github.event.release.tag_name }}"
          release_notes: "${{ github.event.release.name }}
          ${{ github.event.release.body }}"
          visible: 1
          set_rft: 1
