name: manual start

on:
  workflow_dispatch:
    inputs:
      title:
        description: version name
        required: true
      release_notes:
        description: Release notes
        required: true
      visible:
        description: Visible
        required: true
        default: '1'
      set_rft:
        description: Set rft?
        required: true
        default: '1'

jobs:
  CreateNewProductVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sendRequestToVKApi
        uses: iliakologrivov/vkt_new_product_version@master
        env:
          API_TOKEN: ${{ secrets.PRODUCT_API_TOKEN }}
        with:
          token: '123123'
          product_id: 9999